<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>SK 360° | Event Record</title>
    <style>
        *{box-sizing:border-box}
        body{font-family:DejaVu Sans,sans-serif;color:#1f2937;font-size:12px;margin:32px}
        .header{text-align:center;border-bottom:2px solid #b91c1c;padding-bottom:14px;margin-bottom:24px}
        .title{font-size:22px;font-weight:bold;color:#b91c1c;margin:0}
        .subtitle{font-size:11px;color:#6b7280;margin-top:5px}
        .section{margin-bottom:18px}
        .section-title{font-size:12px;font-weight:bold;color:#b91c1c;text-transform:uppercase;margin-bottom:8px}
        .table{width:100%;border-collapse:collapse}
        .table td{border:1px solid #e5e7eb;padding:9px;vertical-align:top}
        .label{width:28%;font-weight:bold;background:#f9fafb;color:#4b5563}
        .description{border:1px solid #e5e7eb;background:#f9fafb;padding:12px;line-height:1.6;min-height:80px}
        .footer{margin-top:28px;padding-top:12px;border-top:1px solid #e5e7eb;font-size:9px;color:#9ca3af;text-align:center}
    </style>
</head>
<body>
    <div class="header">
        <p class="title">SK 360° Event Record</p>
        <p class="subtitle">
            Archived Calendar Record · Administration {{ $administrationLabel }}
        </p>
    </div>
    <div class="section">
        <div class="section-title">Event Information</div>
        <table class="table">
            <tr>
                <td class="label">Event Title</td>
                <td>{{ $event->title ?: 'N/A' }}</td>
            </tr>
            <tr>
                <td class="label">Event Type</td>
                <td>{{ ucwords(str_replace('_',' ',$event->event_type ?? 'event')) }}</td>
            </tr>
            <tr>
                <td class="label">Start</td>
                <td>
                    {{ !empty($event->start_datetime)
                        ? \Carbon\Carbon::parse($event->start_datetime)->format('F d, Y h:i A')
                        : 'N/A' }}
                </td>
            </tr>
            <tr>
                <td class="label">End</td>
                <td>
                    {{ !empty($event->end_datetime)
                        ? \Carbon\Carbon::parse($event->end_datetime)->format('F d, Y h:i A')
                        : 'N/A' }}
                </td>
            </tr>
            <tr>
                <td class="label">Location</td>
                <td>{{ $event->location ?: 'Not specified' }}</td>
            </tr>
            <tr>
                <td class="label">Visibility</td>
                <td>{{ ucwords(str_replace('_',' ',$event->visibility ?? 'public')) }}</td>
            </tr>
            <tr>
                <td class="label">Created By</td>
                <td>
                    {{ trim((string)($event->creator_name ?? ''))
                        ?: 'SK Federation' }}
                </td>
            </tr>
            <tr>
                <td class="label">Administration</td>
                <td>{{ $administrationLabel }}</td>
            </tr>
        </table>
    </div>
    <div class="section">
        <div class="section-title">Description</div>
        <div class="description">
            {{ $event->description ?: 'No description provided.' }}
        </div>
    </div>
    <div class="footer">
        Generated by SK 360° from the archived Calendar event record.
    </div>
</body>
</html>